services:
  server:
    build: ./server
    image: server:v1
    ports:
      - "8080:8080"
    depends_on:
      - apache
      - db
    networks:
      - main
    environment:
      SERVER_ITEM_NAME: ${MYSQL_DATABASE}
      SERVER_ITEM_PORT: ${MYSQL_PORT}
      SERVER_ITEM_HOST: db
      SERVER_ITEM_USER: ${MYSQL_USER}
      SERVER_ITEM_PASSWORD: ${MYSQL_PASSWORD}
      SERVER_PHOTO_ACCESS: ${MINIO_ROOT_USER}
      SERVER_PHOTO_SECRET: ${MINIO_ROOT_PASSWORD}
      SERVER_ITEM_MIGRATION: ${DB_MIGRATION}
    volumes:
      - ./logs/server:/app/logs
      - ./configs/server:/app/config
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./client:/usr/local/apache2/htdocs
      - ./configs/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - main
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    volumes:
      - database:/var/lib/mysql
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - main
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./export:/export
      - ./configs/minio:/root/.minio
    command: server /data --console-address ":9001"

volumes:
  database: {}
  
networks:
  main:
      