services:
  server:
    build: ./server
    image: server:v1
    ports:
      - "8080:8080"
    depends_on:
      - apache
      - db
    networks:
      - main
    environment:
      REST_DB_NAME: ${MYSQL_DATABASE}
      REST_DB_PORT: ${MYSQL_PORT}
      REST_DB_HOST: db
      REST_DB_USER: ${MYSQL_USER}
      REST_DB_PASSWORD: ${MYSQL_PASSWORD}
  apache:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./client/public:/usr/local/apache2/htdocs
      - ./client/httpd.conf:/usr/local/apache2/conf/httpd.conf
  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - main
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    volumes:
      - database:/var/lib/mysql

volumes:
  database: {}
  
networks:
  main:
      